services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - "./server/.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - "./server/.env"
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  
volumes:
  postgres-data: